vim.opt.termguicolors = true  -- Enable true color support
vim.opt.number = true         -- Line numbers
vim.opt.relativenumber = true -- Relative line numbers
vim.opt.showmode = false      -- Don't show mode in command line
vim.opt.cursorline = true     -- Highlight current line
vim.opt.clipboard = "unnamed" -- Sync with system clipboard
vim.opt.undofile = true       -- Save undo history
vim.opt.ignorecase = true     -- Case insensitive search
vim.opt.smartcase = true      -- Case sensitive if uppercase in search
vim.opt.signcolumn = "yes"    -- Always draw sign column
vim.opt.expandtab = true      -- Use spaces instead of tabs
vim.opt.shiftwidth = 4        -- Indent width
vim.opt.smartindent = true    -- Smart autoindenting
vim.opt.laststatus = 3        -- Only one status line
vim.opt.cmdheight = 0         -- Hide command line when it's inactive
vim.opt.autowriteall = true   -- Auto save
vim.opt.confirm = true        -- Confirm to save file before quit Neovim
vim.opt.winborder = "rounded" -- Floating window border style
vim.opt.foldenable = false    -- Don't auto fold when using treesitter folding
vim.opt.scrolloff = 999       -- Keep the cursor line in the middle
vim.opt.list = true           -- Sets how neovim will display certain whitespace characters in the editor
vim.opt.listchars = {
    tab = "  →",
    -- eol = "↲",
    nbsp = "␣",
    trail = "•",
    extends = "❯",
    precedes = "❮",
}
vim.opt.showbreak = "↪" -- String to indicate wrapped lines
vim.opt.completeopt = "menu,popup,menuone,noinsert,noselect" -- Options for completion
vim.opt.sessionoptions = "blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions"
